spring.application.name=Handmade
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/crafty
spring.datasource.username=root
spring.datasource.password=Ravimani1967$
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=727723euit073@skcet.ac.in
spring.mail.password=rsbd gkln rkom hxdd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
